# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(372, 227)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(90, 110, 201, 61))
        self.pushButton.setStyleSheet("QPushButton { \n"
"    color:  #f2b824; \n"
"border: none;\n"
"background-color: #1d1c21; \n"
"font: 18pt \"Centiry Gothic\"\n"
"}\n"
"\n"
"QPushButton:hover { \n"
"color: f2c44e; \n"
"background-color: #3a3c42\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: #eb7b13;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(160, 190, 67, 17))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(40, 20, 311, 70))
        self.textEdit.setStyleSheet("color : #e0bd3f; \n"
"font: 32pt \"Ubuntu\";\n"
"background-color: #1d1c21;\n"
"border: none")
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Узнать погоду"))
        self.label.setText(_translate("Dialog", "Погода"))
